### Intro: find missing data

In [ ]:
import pandas as pd
import numpy as np
import math

crunch = pd.read_csv('crunchbase_monthly_export.csv')
crunch.head()

In [43]:
# Here's building a function using def: 

def square_root(x): return math.sqrt(x)

In [3]:
# Here's building the same function using lambda

square_root = lambda x: math.sqrt(x)
square_root(100)

10.0

In [14]:
# Use the isnull() method to detect the missing values. The output
# shows True when the value is missing. By adding an index into 
# the dataset, you obtain just the entries that are missing.
# A dataset could represent missing data in several ways. In this 
# example, you see missing data represented as np.NaN (NumPy Not 
# a Number) and the Python None value.

print crunch[crunch.isnull()]

#print crunch[crunch.isnull()].index.tolist()

      permalink name homepage_url category_list  market   funding_total_usd   \
0           NaN  NaN          NaN           NaN      NaN                 NaN
1           NaN  NaN          NaN           NaN      NaN                 NaN
2           NaN  NaN          NaN           NaN      NaN                 NaN
3           NaN  NaN          NaN           NaN      NaN                 NaN
4           NaN  NaN          NaN           NaN      NaN                 NaN
5           NaN  NaN          NaN           NaN      NaN                 NaN
6           NaN  NaN          NaN           NaN      NaN                 NaN
7           NaN  NaN          NaN           NaN      NaN                 NaN
8           NaN  NaN          NaN           NaN      NaN                 NaN
9           NaN  NaN          NaN           NaN      NaN                 NaN
10          NaN  NaN          NaN           NaN      NaN                 NaN
11          NaN  NaN          NaN           NaN      NaN                 NaN
12          NaN  NaN          NaN           NaN      NaN                 NaN
13          NaN  NaN          NaN           NaN      NaN                 NaN
14          NaN  NaN          NaN           NaN      NaN                 NaN
15          NaN  NaN          NaN           NaN      NaN                 NaN
16          NaN  NaN          NaN           NaN      NaN                 NaN
17          NaN  NaN          NaN           NaN      NaN                 NaN
18          NaN  NaN          NaN           NaN      NaN                 NaN
19          NaN  NaN          NaN           NaN      NaN                 NaN
20          NaN  NaN          NaN           NaN      NaN                 NaN
21          NaN  NaN          NaN           NaN      NaN                 NaN
22          NaN  NaN          NaN           NaN      NaN                 NaN
23          NaN  NaN          NaN           NaN      NaN                 NaN
24          NaN  NaN          NaN           NaN      NaN                 NaN
25          NaN  NaN          NaN           NaN      NaN                 NaN
26          NaN  NaN          NaN           NaN      NaN                 NaN
27          NaN  NaN          NaN           NaN      NaN                 NaN
28          NaN  NaN          NaN           NaN      NaN                 NaN
29          NaN  NaN          NaN           NaN      NaN                 NaN
...         ...  ...          ...           ...      ...                 ...
44920       NaN  NaN          NaN           NaN      NaN                 NaN
44921       NaN  NaN          NaN           NaN      NaN                 NaN
44922       NaN  NaN          NaN           NaN      NaN                 NaN
44923       NaN  NaN          NaN           NaN      NaN                 NaN
44924       NaN  NaN          NaN           NaN      NaN                 NaN
44925       NaN  NaN          NaN           NaN      NaN                 NaN
44926       NaN  NaN          NaN           NaN      NaN                 NaN
44927       NaN  NaN          NaN           NaN      NaN                 NaN
44928       NaN  NaN          NaN           NaN      NaN                 NaN
44929       NaN  NaN          NaN           NaN      NaN                 NaN
44930       NaN  NaN          NaN           NaN      NaN                 NaN
44931       NaN  NaN          NaN           NaN      NaN                 NaN
44932       NaN  NaN          NaN           NaN      NaN                 NaN
44933       NaN  NaN          NaN           NaN      NaN                 NaN
44934       NaN  NaN          NaN           NaN      NaN                 NaN
44935       NaN  NaN          NaN           NaN      NaN                 NaN
44936       NaN  NaN          NaN           NaN      NaN                 NaN
44937       NaN  NaN          NaN           NaN      NaN                 NaN
44938       NaN  NaN          NaN           NaN      NaN                 NaN
44939       NaN  NaN          NaN           NaN      NaN                 NaN
44940       NaN  NaN          NaN           NaN      NaN                 NaN
44941       NaN  NaN          NaN           NaN      NaN                 NaN
44942       NaN  NaN          NaN           NaN      NaN                 NaN
44943       NaN  NaN          NaN           NaN      NaN                 NaN
44944       NaN  NaN          NaN           NaN      NaN                 NaN
44945       NaN  NaN          NaN           NaN      NaN                 NaN
44946       NaN  NaN          NaN           NaN      NaN                 NaN
44947       NaN  NaN          NaN           NaN      NaN                 NaN
44948       NaN  NaN          NaN           NaN      NaN                 NaN
44949       NaN  NaN          NaN           NaN      NaN                 NaN

      status country_code state_code region city  funding_rounds founded_at  \
0        NaN          NaN        NaN    NaN  NaN             NaN        NaN
1        NaN          NaN        NaN    NaN  NaN             NaN        NaN
2        NaN          NaN        NaN    NaN  NaN             NaN        NaN
3        NaN          NaN        NaN    NaN  NaN             NaN        NaN
4        NaN          NaN        NaN    NaN  NaN             NaN        NaN
5        NaN          NaN        NaN    NaN  NaN             NaN        NaN
6        NaN          NaN        NaN    NaN  NaN             NaN        NaN
7        NaN          NaN        NaN    NaN  NaN             NaN        NaN
8        NaN          NaN        NaN    NaN  NaN             NaN        NaN
9        NaN          NaN        NaN    NaN  NaN             NaN        NaN
10       NaN          NaN        NaN    NaN  NaN             NaN        NaN
11       NaN          NaN        NaN    NaN  NaN             NaN        NaN
12       NaN          NaN        NaN    NaN  NaN             NaN        NaN
13       NaN          NaN        NaN    NaN  NaN             NaN        NaN
14       NaN          NaN        NaN    NaN  NaN             NaN        NaN
15       NaN          NaN        NaN    NaN  NaN             NaN        NaN
16       NaN          NaN        NaN    NaN  NaN             NaN        NaN
17       NaN          NaN        NaN    NaN  NaN             NaN        NaN
18       NaN          NaN        NaN    NaN  NaN             NaN        NaN
19       NaN          NaN        NaN    NaN  NaN             NaN        NaN
20       NaN          NaN        NaN    NaN  NaN             NaN        NaN
21       NaN          NaN        NaN    NaN  NaN             NaN        NaN
22       NaN          NaN        NaN    NaN  NaN             NaN        NaN
23       NaN          NaN        NaN    NaN  NaN             NaN        NaN
24       NaN          NaN        NaN    NaN  NaN             NaN        NaN
25       NaN          NaN        NaN    NaN  NaN             NaN        NaN
26       NaN          NaN        NaN    NaN  NaN             NaN        NaN
27       NaN          NaN        NaN    NaN  NaN             NaN        NaN
28       NaN          NaN        NaN    NaN  NaN             NaN        NaN
29       NaN          NaN        NaN    NaN  NaN             NaN        NaN
...      ...          ...        ...    ...  ...             ...        ...
44920    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44921    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44922    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44923    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44924    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44925    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44926    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44927    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44928    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44929    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44930    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44931    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44932    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44933    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44934    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44935    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44936    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44937    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44938    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44939    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44940    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44941    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44942    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44943    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44944    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44945    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44946    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44947    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44948    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44949    NaN          NaN        NaN    NaN  NaN             NaN        NaN

      founded_month founded_quarter  founded_year first_funding_at  \
0               NaN             NaN           NaN              NaN
1               NaN             NaN           NaN              NaN
2               NaN             NaN           NaN              NaN
3               NaN             NaN           NaN              NaN
4               NaN             NaN           NaN              NaN
5               NaN             NaN           NaN              NaN
6               NaN             NaN           NaN              NaN
7               NaN             NaN           NaN              NaN
8               NaN             NaN           NaN              NaN
9               NaN             NaN           NaN              NaN
10              NaN             NaN           NaN              NaN
11              NaN             NaN           NaN              NaN
12              NaN             NaN           NaN              NaN
13              NaN             NaN           NaN              NaN
14              NaN             NaN           NaN              NaN
15              NaN             NaN           NaN              NaN
16              NaN             NaN           NaN              NaN
17              NaN             NaN           NaN              NaN
18              NaN             NaN           NaN              NaN
19              NaN             NaN           NaN              NaN
20              NaN             NaN           NaN              NaN
21              NaN             NaN           NaN              NaN
22              NaN             NaN           NaN              NaN
23              NaN             NaN           NaN              NaN
24              NaN             NaN           NaN              NaN
25              NaN             NaN           NaN              NaN
26              NaN             NaN           NaN              NaN
27              NaN             NaN           NaN              NaN
28              NaN             NaN           NaN              NaN
29              NaN             NaN           NaN              NaN
...             ...             ...           ...              ...
44920           NaN             NaN           NaN              NaN
44921           NaN             NaN           NaN              NaN
44922           NaN             NaN           NaN              NaN
44923           NaN             NaN           NaN              NaN
44924           NaN             NaN           NaN              NaN
44925           NaN             NaN           NaN              NaN
44926           NaN             NaN           NaN              NaN
44927           NaN             NaN           NaN              NaN
44928           NaN             NaN           NaN              NaN
44929           NaN             NaN           NaN              NaN
44930           NaN             NaN           NaN              NaN
44931           NaN             NaN           NaN              NaN
44932           NaN             NaN           NaN              NaN
44933           NaN             NaN           NaN              NaN
44934           NaN             NaN           NaN              NaN
44935           NaN             NaN           NaN              NaN
44936           NaN             NaN           NaN              NaN
44937           NaN             NaN           NaN              NaN
44938           NaN             NaN           NaN              NaN
44939           NaN             NaN           NaN              NaN
44940           NaN             NaN           NaN              NaN
44941           NaN             NaN           NaN              NaN
44942           NaN             NaN           NaN              NaN
44943           NaN             NaN           NaN              NaN
44944           NaN             NaN           NaN              NaN
44945           NaN             NaN           NaN              NaN
44946           NaN             NaN           NaN              NaN
44947           NaN             NaN           NaN              NaN
44948           NaN             NaN           NaN              NaN
44949           NaN             NaN           NaN              NaN

      last_funding_at  Unnamed: 18
0                 NaN          NaN
1                 NaN          NaN
2                 NaN          NaN
3                 NaN          NaN
4                 NaN          NaN
5                 NaN          NaN
6                 NaN          NaN
7                 NaN          NaN
8                 NaN          NaN
9                 NaN          NaN
10                NaN          NaN
11                NaN          NaN
12                NaN          NaN
13                NaN          NaN
14                NaN          NaN
15                NaN          NaN
16                NaN          NaN
17                NaN          NaN
18                NaN          NaN
19                NaN          NaN
20                NaN          NaN
21                NaN          NaN
22                NaN          NaN
23                NaN          NaN
24                NaN          NaN
25                NaN          NaN
26                NaN          NaN
27                NaN          NaN
28                NaN          NaN
29                NaN          NaN
...               ...          ...
44920             NaN          NaN
44921             NaN          NaN
44922             NaN          NaN
44923             NaN          NaN
44924             NaN          NaN
44925             NaN          NaN
44926             NaN          NaN
44927             NaN          NaN
44928             NaN          NaN
44929             NaN          NaN
44930             NaN          NaN
44931             NaN          NaN
44932             NaN          NaN
44933             NaN          NaN
44934             NaN          NaN
44935             NaN          NaN
44936             NaN          NaN
44937             NaN          NaN
44938             NaN          NaN
44939             NaN          NaN
44940             NaN          NaN
44941             NaN          NaN
44942             NaN          NaN
44943             NaN          NaN
44944             NaN          NaN
44945             NaN          NaN
44946             NaN          NaN
44947             NaN          NaN
44948             NaN          NaN
44949             NaN          NaN

[44950 rows x 19 columns]

### Intro: fill in missing data

In [ ]:
# To fill in missing data use fillna(). For fillna() you need to 
# provide a number. Usually, the mean, median, or mode is used. 
# Let's use the same data set and this time let's fill in missing 
# values with the mean. 

print crunch.fillna(int(crunch.mean()))

In [16]:
# We could also just drop all the NAs, by using dropna()

crunch.dropna()

Empty DataFrame
Columns: [permalink, name, homepage_url, category_list,  market ,  funding_total_usd , status, country_code, state_code, region, city, funding_rounds, founded_at, founded_month, founded_quarter, founded_year, first_funding_at, last_funding_at, Unnamed: 18]
Index: []

### Write the equivalent lambda function

In [18]:
# Write the equivalent lambda function for the following def 
# function:

In [17]:
# equivalent lambda function

def f (x): return x**2
print f(8)

squared = lambda x: x**2
squared(10)

64

100

### Lab 3.4

In [19]:
# read in the raw data from the github url

data = pd.read_csv("https://raw.githubusercontent.com/suneel0101/lesson-plan/master/crunchbase_monthly_export.csv")

In [20]:
# find missing values

print data[data.isnull()]

      permalink name homepage_url category_list  market   funding_total_usd   \
0           NaN  NaN          NaN           NaN      NaN                 NaN
1           NaN  NaN          NaN           NaN      NaN                 NaN
2           NaN  NaN          NaN           NaN      NaN                 NaN
3           NaN  NaN          NaN           NaN      NaN                 NaN
4           NaN  NaN          NaN           NaN      NaN                 NaN
5           NaN  NaN          NaN           NaN      NaN                 NaN
6           NaN  NaN          NaN           NaN      NaN                 NaN
7           NaN  NaN          NaN           NaN      NaN                 NaN
8           NaN  NaN          NaN           NaN      NaN                 NaN
9           NaN  NaN          NaN           NaN      NaN                 NaN
10          NaN  NaN          NaN           NaN      NaN                 NaN
11          NaN  NaN          NaN           NaN      NaN                 NaN
12          NaN  NaN          NaN           NaN      NaN                 NaN
13          NaN  NaN          NaN           NaN      NaN                 NaN
14          NaN  NaN          NaN           NaN      NaN                 NaN
15          NaN  NaN          NaN           NaN      NaN                 NaN
16          NaN  NaN          NaN           NaN      NaN                 NaN
17          NaN  NaN          NaN           NaN      NaN                 NaN
18          NaN  NaN          NaN           NaN      NaN                 NaN
19          NaN  NaN          NaN           NaN      NaN                 NaN
20          NaN  NaN          NaN           NaN      NaN                 NaN
21          NaN  NaN          NaN           NaN      NaN                 NaN
22          NaN  NaN          NaN           NaN      NaN                 NaN
23          NaN  NaN          NaN           NaN      NaN                 NaN
24          NaN  NaN          NaN           NaN      NaN                 NaN
25          NaN  NaN          NaN           NaN      NaN                 NaN
26          NaN  NaN          NaN           NaN      NaN                 NaN
27          NaN  NaN          NaN           NaN      NaN                 NaN
28          NaN  NaN          NaN           NaN      NaN                 NaN
29          NaN  NaN          NaN           NaN      NaN                 NaN
...         ...  ...          ...           ...      ...                 ...
44920       NaN  NaN          NaN           NaN      NaN                 NaN
44921       NaN  NaN          NaN           NaN      NaN                 NaN
44922       NaN  NaN          NaN           NaN      NaN                 NaN
44923       NaN  NaN          NaN           NaN      NaN                 NaN
44924       NaN  NaN          NaN           NaN      NaN                 NaN
44925       NaN  NaN          NaN           NaN      NaN                 NaN
44926       NaN  NaN          NaN           NaN      NaN                 NaN
44927       NaN  NaN          NaN           NaN      NaN                 NaN
44928       NaN  NaN          NaN           NaN      NaN                 NaN
44929       NaN  NaN          NaN           NaN      NaN                 NaN
44930       NaN  NaN          NaN           NaN      NaN                 NaN
44931       NaN  NaN          NaN           NaN      NaN                 NaN
44932       NaN  NaN          NaN           NaN      NaN                 NaN
44933       NaN  NaN          NaN           NaN      NaN                 NaN
44934       NaN  NaN          NaN           NaN      NaN                 NaN
44935       NaN  NaN          NaN           NaN      NaN                 NaN
44936       NaN  NaN          NaN           NaN      NaN                 NaN
44937       NaN  NaN          NaN           NaN      NaN                 NaN
44938       NaN  NaN          NaN           NaN      NaN                 NaN
44939       NaN  NaN          NaN           NaN      NaN                 NaN
44940       NaN  NaN          NaN           NaN      NaN                 NaN
44941       NaN  NaN          NaN           NaN      NaN                 NaN
44942       NaN  NaN          NaN           NaN      NaN                 NaN
44943       NaN  NaN          NaN           NaN      NaN                 NaN
44944       NaN  NaN          NaN           NaN      NaN                 NaN
44945       NaN  NaN          NaN           NaN      NaN                 NaN
44946       NaN  NaN          NaN           NaN      NaN                 NaN
44947       NaN  NaN          NaN           NaN      NaN                 NaN
44948       NaN  NaN          NaN           NaN      NaN                 NaN
44949       NaN  NaN          NaN           NaN      NaN                 NaN

      status country_code state_code region city  funding_rounds founded_at  \
0        NaN          NaN        NaN    NaN  NaN             NaN        NaN
1        NaN          NaN        NaN    NaN  NaN             NaN        NaN
2        NaN          NaN        NaN    NaN  NaN             NaN        NaN
3        NaN          NaN        NaN    NaN  NaN             NaN        NaN
4        NaN          NaN        NaN    NaN  NaN             NaN        NaN
5        NaN          NaN        NaN    NaN  NaN             NaN        NaN
6        NaN          NaN        NaN    NaN  NaN             NaN        NaN
7        NaN          NaN        NaN    NaN  NaN             NaN        NaN
8        NaN          NaN        NaN    NaN  NaN             NaN        NaN
9        NaN          NaN        NaN    NaN  NaN             NaN        NaN
10       NaN          NaN        NaN    NaN  NaN             NaN        NaN
11       NaN          NaN        NaN    NaN  NaN             NaN        NaN
12       NaN          NaN        NaN    NaN  NaN             NaN        NaN
13       NaN          NaN        NaN    NaN  NaN             NaN        NaN
14       NaN          NaN        NaN    NaN  NaN             NaN        NaN
15       NaN          NaN        NaN    NaN  NaN             NaN        NaN
16       NaN          NaN        NaN    NaN  NaN             NaN        NaN
17       NaN          NaN        NaN    NaN  NaN             NaN        NaN
18       NaN          NaN        NaN    NaN  NaN             NaN        NaN
19       NaN          NaN        NaN    NaN  NaN             NaN        NaN
20       NaN          NaN        NaN    NaN  NaN             NaN        NaN
21       NaN          NaN        NaN    NaN  NaN             NaN        NaN
22       NaN          NaN        NaN    NaN  NaN             NaN        NaN
23       NaN          NaN        NaN    NaN  NaN             NaN        NaN
24       NaN          NaN        NaN    NaN  NaN             NaN        NaN
25       NaN          NaN        NaN    NaN  NaN             NaN        NaN
26       NaN          NaN        NaN    NaN  NaN             NaN        NaN
27       NaN          NaN        NaN    NaN  NaN             NaN        NaN
28       NaN          NaN        NaN    NaN  NaN             NaN        NaN
29       NaN          NaN        NaN    NaN  NaN             NaN        NaN
...      ...          ...        ...    ...  ...             ...        ...
44920    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44921    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44922    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44923    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44924    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44925    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44926    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44927    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44928    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44929    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44930    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44931    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44932    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44933    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44934    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44935    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44936    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44937    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44938    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44939    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44940    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44941    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44942    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44943    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44944    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44945    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44946    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44947    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44948    NaN          NaN        NaN    NaN  NaN             NaN        NaN
44949    NaN          NaN        NaN    NaN  NaN             NaN        NaN

      founded_month founded_quarter  founded_year first_funding_at  \
0               NaN             NaN           NaN              NaN
1               NaN             NaN           NaN              NaN
2               NaN             NaN           NaN              NaN
3               NaN             NaN           NaN              NaN
4               NaN             NaN           NaN              NaN
5               NaN             NaN           NaN              NaN
6               NaN             NaN           NaN              NaN
7               NaN             NaN           NaN              NaN
8               NaN             NaN           NaN              NaN
9               NaN             NaN           NaN              NaN
10              NaN             NaN           NaN              NaN
11              NaN             NaN           NaN              NaN
12              NaN             NaN           NaN              NaN
13              NaN             NaN           NaN              NaN
14              NaN             NaN           NaN              NaN
15              NaN             NaN           NaN              NaN
16              NaN             NaN           NaN              NaN
17              NaN             NaN           NaN              NaN
18              NaN             NaN           NaN              NaN
19              NaN             NaN           NaN              NaN
20              NaN             NaN           NaN              NaN
21              NaN             NaN           NaN              NaN
22              NaN             NaN           NaN              NaN
23              NaN             NaN           NaN              NaN
24              NaN             NaN           NaN              NaN
25              NaN             NaN           NaN              NaN
26              NaN             NaN           NaN              NaN
27              NaN             NaN           NaN              NaN
28              NaN             NaN           NaN              NaN
29              NaN             NaN           NaN              NaN
...             ...             ...           ...              ...
44920           NaN             NaN           NaN              NaN
44921           NaN             NaN           NaN              NaN
44922           NaN             NaN           NaN              NaN
44923           NaN             NaN           NaN              NaN
44924           NaN             NaN           NaN              NaN
44925           NaN             NaN           NaN              NaN
44926           NaN             NaN           NaN              NaN
44927           NaN             NaN           NaN              NaN
44928           NaN             NaN           NaN              NaN
44929           NaN             NaN           NaN              NaN
44930           NaN             NaN           NaN              NaN
44931           NaN             NaN           NaN              NaN
44932           NaN             NaN           NaN              NaN
44933           NaN             NaN           NaN              NaN
44934           NaN             NaN           NaN              NaN
44935           NaN             NaN           NaN              NaN
44936           NaN             NaN           NaN              NaN
44937           NaN             NaN           NaN              NaN
44938           NaN             NaN           NaN              NaN
44939           NaN             NaN           NaN              NaN
44940           NaN             NaN           NaN              NaN
44941           NaN             NaN           NaN              NaN
44942           NaN             NaN           NaN              NaN
44943           NaN             NaN           NaN              NaN
44944           NaN             NaN           NaN              NaN
44945           NaN             NaN           NaN              NaN
44946           NaN             NaN           NaN              NaN
44947           NaN             NaN           NaN              NaN
44948           NaN             NaN           NaN              NaN
44949           NaN             NaN           NaN              NaN

      last_funding_at  Unnamed: 18
0                 NaN          NaN
1                 NaN          NaN
2                 NaN          NaN
3                 NaN          NaN
4                 NaN          NaN
5                 NaN          NaN
6                 NaN          NaN
7                 NaN          NaN
8                 NaN          NaN
9                 NaN          NaN
10                NaN          NaN
11                NaN          NaN
12                NaN          NaN
13                NaN          NaN
14                NaN          NaN
15                NaN          NaN
16                NaN          NaN
17                NaN          NaN
18                NaN          NaN
19                NaN          NaN
20                NaN          NaN
21                NaN          NaN
22                NaN          NaN
23                NaN          NaN
24                NaN          NaN
25                NaN          NaN
26                NaN          NaN
27                NaN          NaN
28                NaN          NaN
29                NaN          NaN
...               ...          ...
44920             NaN          NaN
44921             NaN          NaN
44922             NaN          NaN
44923             NaN          NaN
44924             NaN          NaN
44925             NaN          NaN
44926             NaN          NaN
44927             NaN          NaN
44928             NaN          NaN
44929             NaN          NaN
44930             NaN          NaN
44931             NaN          NaN
44932             NaN          NaN
44933             NaN          NaN
44934             NaN          NaN
44935             NaN          NaN
44936             NaN          NaN
44937             NaN          NaN
44938             NaN          NaN
44939             NaN          NaN
44940             NaN          NaN
44941             NaN          NaN
44942             NaN          NaN
44943             NaN          NaN
44944             NaN          NaN
44945             NaN          NaN
44946             NaN          NaN
44947             NaN          NaN
44948             NaN          NaN
44949             NaN          NaN

[44950 rows x 19 columns]

In [ ]:
# fill in missing data with the mean

data.fillna(int(data.mean()))